[compiler.solc]
ignore_paths = ["source/node_modules", "source/lib", "source/old_test", "source/test", "source/scripts"]
include_paths = ["source/node_modules"]
evm_version = "london"

[compiler.solc.optimizer]
enabled = true
